apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - name: frontend
          image: gcr.io/workflow-283323/frontend
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
      containers:
        - name: backend
          image: gcr.io/workflow-283323/backend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
              
      containers:
        - name: worker
          image: gcr.io/workflow-283323/worker
          ports:
            - containerPort: 6969
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
