apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend_tasks
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: backend_tasts
    spec:
      containers:
        - name: backend_tasks
          image: gcr.io/workflow-283323/static-site:worker	
          ports:
            - containerPort: 5555
          resources:
            requests:
              cpu: "0.1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
