apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/workflow-283323/static-site:backend	
          ports:
            - containerPort: 5050
          resources:
            requests:
              cpu: "0.1"
              memory: "512Mi"
            limits:
              cpu: "4"
              memory: "2Gi"
