apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-frontend.yml
  - deployment-backendtasks.yml
  - deployment-backend.yml
  - postgres-service.yaml
  - deployment-postgres.yml
