apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: postgres
    spec:
      schedulerName: stork
      containers:
        - name: postgres
          image: postgres:12
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          
          volumes:
            - name: postgredb
              persistentVolumeClaim:
                claimName: px-postgres-pvc

          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
